export const DEFAULT_FALLBACK_PRICES = {
  BTC: 65000,
  ETH: 3500,
  DEFAULT: 100,
} as const;

export const DATABASE_CONFIG = {
  DEFAULT_POOL_SIZE: 20,
  DEFAULT_IDLE_TIMEOUT: 30000,
  DEFAULT_CONNECTION_TIMEOUT: 5000,
  DEFAULT_MAX_USES: 7500,
} as const;

export const RATE_LIMIT_CONFIG = {
  DEFAULT_MEMORY_LIMIT: 5000,
  DEFAULT_WINDOW_MS: 60000,
  DEFAULT_MAX_REQUESTS: 100,
} as const;

export const ORACLE_CONFIG = {
  DEFAULT_MEMORY_MAX_VOTE_KEYS: 200_000,
  DEFAULT_MEMORY_VOTE_BLOCK_WINDOW: 50_000n,
  DEFAULT_MEMORY_MAX_ASSERTIONS: 10_000,
  DEFAULT_MEMORY_MAX_DISPUTES: 10_000,
  DEFAULT_SYNC_METRICS_LIMIT: 600,
  DEFAULT_SYNC_METRICS_MAX_AGE_MINUTES: 24 * 60,
  DEFAULT_ORACLE_EVENTS_MAX_SIZE: 2000,
  DEFAULT_BATCH_SIZE: 100,
  DEFAULT_PRICE_FETCH_TIMEOUT: 5000,
  DEFAULT_PRICE_FETCH_RETRY_DELAY: 1000,
} as const;

export const CHART_CONFIG = {
  DEFAULT_CHART_LIMIT: 720,
  DEFAULT_CHART_MINUTES: 360,
  DEFAULT_MARKET_STATS_DAYS: 30,
  DEFAULT_MARKET_STATS_LIMIT: 10,
  DEFAULT_ACCURACY_DAYS: 30,
  DEFAULT_ACCURACY_SYMBOL: 'ETH',
  ACCURACY_THRESHOLD_WARNING: 0.02,
  ACCURACY_THRESHOLD_CRITICAL: 0.05,
  MAX_ANOMALIES: 5,
} as const;

export const API_CONFIG = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DEFAULT_SORT_ORDER: 'desc',
  MAX_REQUEST_BODY_SIZE: '10mb',
  DEFAULT_TIMEOUT: 30000,
} as const;

export const CACHE_CONFIG = {
  DEFAULT_LRU_CACHE_SIZE: 1000,
  DEFAULT_CACHE_TTL: 300000, // 5 minutes
  DEFAULT_DEDUPING_INTERVAL: 15000,
  DEFAULT_REFRESH_INTERVAL: 30000,
} as const;

export const SECURITY_CONFIG = {
  MAX_URL_LENGTH: 2048,
  MAX_QUERY_STRING_LENGTH: 1024,
  MAX_HEADER_SIZE: 8192,
  DEFAULT_TOKEN_LENGTH: 32,
  DEFAULT_SIGNATURE_LENGTH: 132,
} as const;

export const VALIDATION_CONFIG = {
  MIN_ADDRESS_LENGTH: 40,
  MAX_ADDRESS_LENGTH: 42,
  MIN_TX_HASH_LENGTH: 64,
  MAX_TX_HASH_LENGTH: 66,
  MIN_PRIVATE_KEY_LENGTH: 64,
  MAX_PRIVATE_KEY_LENGTH: 66,
  DEFAULT_STRING_MAX_LENGTH: 255,
  DEFAULT_TEXT_MAX_LENGTH: 65535,
} as const;

export const NETWORK_CONFIG = {
  DEFAULT_RPC_TIMEOUT: 30000,
  DEFAULT_RPC_RETRY_ATTEMPTS: 3,
  DEFAULT_RPC_RETRY_DELAY: 1000,
  DEFAULT_BLOCK_CONFIRMATIONS: 2,
  DEFAULT_GAS_PRICE_MULTIPLIER: 1.1,
} as const;

export const MONITORING_CONFIG = {
  DEFAULT_HEALTH_CHECK_INTERVAL: 30000,
  DEFAULT_METRICS_RETENTION_DAYS: 30,
  DEFAULT_ALERT_COOLDOWN_MINUTES: 5,
  DEFAULT_ANOMALY_DETECTION_WINDOW: 24 * 60 * 60 * 1000, // 24 hours
} as const;
