/**
 * Application Configuration Constants
 *
 * 统一的应用配置常量
 */

export const APP_CONFIG = {
  API: {
    DEFAULT_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000',
    DEFAULT_TIMEOUT_MS: 30000,
    HEALTH_CHECK_INTERVAL_MS: 60000,
  },

  CACHE: {
    PRICE_TTL_MS: 30000,
    AGGREGATION_TTL_MS: 30000,
    DEFAULT_TTL_MS: 60000,
    MAX_CACHE_SIZE: 1000,
  },

  SYNC: {
    AGGREGATION_INTERVAL_MS: 5000,
    DEFAULT_RETRY_DELAY_MS: 5000,
    MAX_RETRY_ATTEMPTS: 3,
  },

  TRADING: {
    DEFAULT_TRADE_AMOUNT: 10000,
    MIN_PROFIT_THRESHOLD_PERCENT: 0.5,
    MAX_PRICE_DEVIATION_PERCENT: 5,
  },

  THRESHOLDS: {
    ERROR_THRESHOLD: 3,
    CRITICAL_ERROR_THRESHOLD: 5,
    ALERT_COOLDOWN_MS: 60000,
  },

  UI: {
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
    DEBOUNCE_DELAY_MS: 300,
    ANIMATION_DURATION_MS: 300,
  },
} as const;

export const ERROR_CODES = {
  NETWORK_ERROR: 'network_error',
  TIMEOUT: 'timeout',
  API_ERROR: 'api_error',
  VALIDATION_ERROR: 'validation_error',
  UNKNOWN_ERROR: 'unknown_error',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
